#prettier-ignore
rule_cat = {
    'cat1': [{'rule': 'ruleC1R1', 'severity': 'Warning'}, {'rule': 'ruleC1R2', 'severity': 'Warning'}],
    'cat2': [{'rule': 'ruleC2R1', 'severity': 'Error'}, {'rule': 'ruleC2R2', 'severity': 'Fatal'}],
    'cat3': [{'rule': 'ruleC3R1', 'severity': 'Fatal'}, {'rule': 'ruleC3R2', 'severity': 'Warning'}, {'rule': 'ruleC3R3', 'severity': 'Error'}],
    'cat4': [{'rule': 'ruleC4R1', 'severity': 'Error'}],
    'cat5': [{'rule': 'ruleC5R1', 'severity': 'Warning'}, {'rule': 'ruleC5R2', 'severity': 'Fatal'}],
    'cat6': [{'rule': 'ruleC6R1', 'severity': 'Fatal'}],
    'cat7': [{'rule': 'ruleC7R1', 'severity': 'Warning'}, {'rule': 'ruleC7R2', 'severity': 'Error'}],
    'cat8': [{'rule': 'ruleC8R1', 'severity': 'Error'}, {'rule': 'ruleC8R2', 'severity': 'Warning'}, {'rule': 'ruleC8R3', 'severity': 'Fatal'}],
    'cat9': [{'rule': 'ruleC9R1', 'severity': 'Fatal'}],
    'cat10': [{'rule': 'ruleC10R1', 'severity': 'Warning'}],
    'cat11': [{'rule': 'ruleC11R1', 'severity': 'Error'}, {'rule': 'ruleC11R2', 'severity': 'Warning'}],
    'cat12': [{'rule': 'ruleC12R1', 'severity': 'Fatal'}, {'rule': 'ruleC12R2', 'severity': 'Error'}],
    'cat13': [{'rule': 'ruleC13R1', 'severity': 'Warning'}],
    'cat14': [{'rule': 'ruleC14R1', 'severity': 'Error'}, {'rule': 'ruleC14R2', 'severity': 'Fatal'}, {'rule': 'ruleC14R3', 'severity': 'Warning'}],
    'cat15': [{'rule': 'ruleC15R1', 'severity': 'Fatal'}],
    'cat16': [{'rule': 'ruleC16R1', 'severity': 'Warning'}, {'rule': 'ruleC16R2', 'severity': 'Error'}],
    'cat17': [{'rule': 'ruleC17R1', 'severity': 'Error'}],
    'cat18': [{'rule': 'ruleC18R1', 'severity': 'Fatal'}, {'rule': 'ruleC18R2', 'severity': 'Warning'}],
    'cat19': [{'rule': 'ruleC19R1', 'severity': 'Warning'}, {'rule': 'ruleC19R2', 'severity': 'Error'}, {'rule': 'ruleC19R3', 'severity': 'Fatal'}],
    'cat20': [{'rule': 'ruleC20R1', 'severity': 'Error'}],
    'cat21': [{'rule': 'ruleC21R1', 'severity': 'Fatal'}, {'rule': 'ruleC21R2', 'severity': 'Warning'}],
}


#prettier-ignore
pin_data = {
  "pin1": {
    "rules": {
      "cat1__ruleC1R1": {"cat": "cat1", "rule": "ruleC1R1", "status": "passed", "details": """
app_settings:
  app_name: "My YAML App"
  version: 1.2.1
  maintenance_mode: false
  
  # Example of a multi-line string (preserves newlines)
  welcome_message: |
    Hello,
    Welcome to the application.
    Please log in to continue.

  # Example of a folded string (converts to a single line)
  system_notice: >
    This system will be down
    for scheduled maintenance
    on Sunday at 2:00 AM UTC.
                         
                         """},
      "cat1__ruleC1R2": {"cat": "cat1", "rule": "ruleC1R2", "status": "failed", "details": "this is the cat1 ruleC1R2 failed details"},
      "cat2__ruleC2R1": {"cat": "cat2", "rule": "ruleC2R1", "status": "N/A", "details": "this is the cat2 ruleC2R1 N/A details"},
      "cat3__ruleC3R1": {"cat": "cat3", "rule": "ruleC3R1", "status": "passed", "details": "this is the cat3 ruleC3R1 passed details"},
      "cat4__ruleC4R1": {"cat": "cat4", "rule": "ruleC4R1", "status": "failed", "details": "this is the cat4 ruleC4R1 failed details"},
      "cat5__ruleC5R1": {"cat": "cat5", "rule": "ruleC5R1", "status": "N/A", "details": "this is the cat5 ruleC5R1 N/A details"},
      "cat6__ruleC6R1": {"cat": "cat6", "rule": "ruleC6R1", "status": "passed", "details": "this is the cat6 ruleC6R1 passed details"},
      "cat7__ruleC7R1": {"cat": "cat7", "rule": "ruleC7R1", "status": "failed", "details": "this is the cat7 ruleC7R1 failed details"},
      "cat8__ruleC8R1": {"cat": "cat8", "rule": "ruleC8R1", "status": "N/A", "details": "this is the cat8 ruleC8R1 N/A details"},
      "cat9__ruleC9R1": {"cat": "cat9", "rule": "ruleC9R1", "status": "passed", "details": "this is the cat9 ruleC9R1 passed details"},
      "cat10__ruleC10R1": {"cat": "cat10", "rule": "ruleC10R1", "status": "failed", "details": "this is the cat10 ruleC10R1 failed details"},
      "cat11__ruleC11R1": {"cat": "cat11", "rule": "ruleC11R1", "status": "N/A", "details": "this is the cat11 ruleC11R1 N/A details"},
      "cat12__ruleC12R1": {"cat": "cat12", "rule": "ruleC12R1", "status": "passed", "details": "this is the cat12 ruleC12R1 passed details"},
      "cat13__ruleC13R1": {"cat": "cat13", "rule": "ruleC13R1", "status": "failed", "details": "this is the cat13 ruleC13R1 failed details"},
      "cat14__ruleC14R1": {"cat": "cat14", "rule": "ruleC14R1", "status": "N/A", "details": "this is the cat14 ruleC14R1 N/A details"},
      "cat15__ruleC15R1": {"cat": "cat15", "rule": "ruleC15R1", "status": "passed", "details": "this is the cat15 ruleC15R1 passed details"},
      "cat16__ruleC16R1": {"cat": "cat16", "rule": "ruleC16R1", "status": "failed", "details": "this is the cat16 ruleC16R1 failed details"},
      "cat17__ruleC17R1": {"cat": "cat17", "rule": "ruleC17R1", "status": "N/A", "details": "this is the cat17 ruleC17R1 N/A details"},
      "cat18__ruleC18R1": {"cat": "cat18", "rule": "ruleC18R1", "status": "passed", "details": "this is the cat18 ruleC18R1 passed details"},
      "cat19__ruleC19R1": {"cat": "cat19", "rule": "ruleC19R1", "status": "failed", "details": "this is the cat19 ruleC19R1 failed details"},
      "cat20__ruleC20R1": {"cat": "cat20", "rule": "ruleC20R1", "status": "N/A", "details": "this is the cat20 ruleC20R1 N/A details"},
      "cat21__ruleC21R1": {"cat": "cat21", "rule": "ruleC21R1", "status": "passed", "details": "this is the cat21 ruleC21R1 passed details"}
    },
    "pin_direction": "horizontal",
    "pin_details": "this is the pin details of pin1"
  },
  "pin2": {
    "rules": {
      "cat1__ruleC1R1": {"cat": "cat1", "rule": "ruleC1R1", "status": "failed", "details": "this is the cat1 ruleC1R1 failed details"},
      "cat1__ruleC1R2": {"cat": "cat1", "rule": "ruleC1R2", "status": "passed", "details": "this is the cat1 ruleC1R2 passed details"},
      "cat2__ruleC2R1": {"cat": "cat2", "rule": "ruleC2R1", "status": "N/A", "details": "this is the cat2 ruleC2R1 N/A details"},
      "cat3__ruleC3R1": {"cat": "cat3", "rule": "ruleC3R1", "status": "failed", "details": "this is the cat3 ruleC3R1 failed details"},
      "cat4__ruleC4R1": {"cat": "cat4", "rule": "ruleC4R1", "status": "passed", "details": "this is the cat4 ruleC4R1 passed details"},
      "cat5__ruleC5R1": {"cat": "cat5", "rule": "ruleC5R1", "status": "N/A", "details": "this is the cat5 ruleC5R1 N/A details"},
      "cat6__ruleC6R1": {"cat": "cat6", "rule": "ruleC6R1", "status": "failed", "details": "this is the cat6 ruleC6R1 failed details"},
      "cat7__ruleC7R1": {"cat": "cat7", "rule": "ruleC7R1", "status": "passed", "details": "this is the cat7 ruleC7R1 passed details"},
      "cat8__ruleC8R1": {"cat": "cat8", "rule": "ruleC8R1", "status": "N/A", "details": "this is the cat8 ruleC8R1 N/A details"},
      "cat9__ruleC9R1": {"cat": "cat9", "rule": "ruleC9R1", "status": "failed", "details": "this is the cat9 ruleC9R1 failed details"},
      "cat10__ruleC10R1": {"cat": "cat10", "rule": "ruleC10R1", "status": "passed", "details": "this is the cat10 ruleC10R1 passed details"},
      "cat11__ruleC11R1": {"cat": "cat11", "rule": "ruleC11R1", "status": "N/A", "details": "this is the cat11 ruleC11R1 N/A details"},
      "cat12__ruleC12R1": {"cat": "cat12", "rule": "ruleC12R1", "status": "failed", "details": "this is the cat12 ruleC12R1 failed details"},
      "cat13__ruleC13R1": {"cat": "cat13", "rule": "ruleC13R1", "status": "passed", "details": "this is the cat13 ruleC13R1 passed details"},
      "cat14__ruleC14R1": {"cat": "cat14", "rule": "ruleC14R1", "status": "N/A", "details": "this is the cat14 ruleC14R1 N/A details"},
      "cat15__ruleC15R1": {"cat": "cat15", "rule": "ruleC15R1", "status": "failed", "details": "this is the cat15 ruleC15R1 failed details"},
      "cat16__ruleC16R1": {"cat": "cat16", "rule": "ruleC16R1", "status": "passed", "details": "this is the cat16 ruleC16R1 passed details"},
      "cat17__ruleC17R1": {"cat": "cat17", "rule": "ruleC17R1", "status": "N/A", "details": "this is the cat17 ruleC17R1 N/A details"},
      "cat18__ruleC18R1": {"cat": "cat18", "rule": "ruleC18R1", "status": "failed", "details": "this is the cat18 ruleC18R1 failed details"},
      "cat19__ruleC19R1": {"cat": "cat19", "rule": "ruleC19R1", "status": "passed", "details": "this is the cat19 ruleC19R1 passed details"},
      "cat20__ruleC20R1": {"cat": "cat20", "rule": "ruleC20R1", "status": "N/A", "details": "this is the cat20 ruleC20R1 N/A details"},
      "cat21__ruleC21R1": {"cat": "cat21", "rule": "ruleC21R1", "status": "failed", "details": "this is the cat21 ruleC21R1 failed details"}
    },
    "pin_direction": "vertical",
    "pin_details": "this is the pin details of pin2"
  },
  "pin3": {
    "rules": {
      "cat1__ruleC1R1": {"cat": "cat1", "rule": "ruleC1R1", "status": "N/A", "details": "this is the cat1 ruleC1R1 N/A details"},
      "cat1__ruleC1R2": {"cat": "cat1", "rule": "ruleC1R2", "status": "failed", "details": "this is the cat1 ruleC1R2 failed details"},
      "cat2__ruleC2R1": {"cat": "cat2", "rule": "ruleC2R1", "status": "passed", "details": "this is the cat2 ruleC2R1 passed details"},
      "cat3__ruleC3R1": {"cat": "cat3", "rule": "ruleC3R1", "status": "N/A", "details": "this is the cat3 ruleC3R1 N/A details"},
      "cat4__ruleC4R1": {"cat": "cat4", "rule": "ruleC4R1", "status": "failed", "details": "this is the cat4 ruleC4R1 failed details"},
      "cat5__ruleC5R1": {"cat": "cat5", "rule": "ruleC5R1", "status": "passed", "details": "this is the cat5 ruleC5R1 passed details"},
      "cat6__ruleC6R1": {"cat": "cat6", "rule": "ruleC6R1", "status": "N/A", "details": "this is the cat6 ruleC6R1 N/A details"},
      "cat7__ruleC7R1": {"cat": "cat7", "rule": "ruleC7R1", "status": "failed", "details": "this is the cat7 ruleC7R1 failed details"},
      "cat8__ruleC8R1": {"cat": "cat8", "rule": "ruleC8R1", "status": "passed", "details": "this is the cat8 ruleC8R1 passed details"},
      "cat9__ruleC9R1": {"cat": "cat9", "rule": "ruleC9R1", "status": "N/A", "details": "this is the cat9 ruleC9R1 N/A details"},
      "cat10__ruleC10R1": {"cat": "cat10", "rule": "ruleC10R1", "status": "failed", "details": "this is the cat10 ruleC10R1 failed details"},
      "cat11__ruleC11R1": {"cat": "cat11", "rule": "ruleC11R1", "status": "passed", "details": "this is the cat11 ruleC11R1 passed details"},
      "cat12__ruleC12R1": {"cat": "cat12", "rule": "ruleC12R1", "status": "N/A", "details": "this is the cat12 ruleC12R1 N/A details"},
      "cat13__ruleC13R1": {"cat": "cat13", "rule": "ruleC13R1", "status": "failed", "details": "this is the cat13 ruleC13R1 failed details"},
      "cat14__ruleC14R1": {"cat": "cat14", "rule": "ruleC14R1", "status": "passed", "details": "this is the cat14 ruleC14R1 passed details"},
      "cat15__ruleC15R1": {"cat": "cat15", "rule": "ruleC15R1", "status": "N/A", "details": "this is the cat15 ruleC15R1 N/A details"},
      "cat16__ruleC16R1": {"cat": "cat16", "rule": "ruleC16R1", "status": "failed", "details": "this is the cat16 ruleC16R1 failed details"},
      "cat17__ruleC17R1": {"cat": "cat17", "rule": "ruleC17R1", "status": "passed", "details": "this is the cat17 ruleC17R1 passed details"},
      "cat18__ruleC18R1": {"cat": "cat18", "rule": "ruleC18R1", "status": "N/A", "details": "this is the cat18 ruleC18R1 N/A details"},
      "cat19__ruleC19R1": {"cat": "cat19", "rule": "ruleC19R1", "status": "failed", "details": "this is the cat19 ruleC19R1 failed details"},
      "cat20__ruleC20R1": {"cat": "cat20", "rule": "ruleC20R1", "status": "passed", "details": "this is the cat20 ruleC20R1 passed details"},
      "cat21__ruleC21R1": {"cat": "cat21", "rule": "ruleC21R1", "status": "N/A", "details": "this is the cat21 ruleC21R1 N/A details"}
    },
    "pin_direction": "horizontal",
    "pin_details": "this is the pin details of pin3"
  },
  "pin4": {
    "rules": {
      "cat1__ruleC1R1": {"cat": "cat1", "rule": "ruleC1R1", "status": "passed", "details": "this is the cat1 ruleC1R1 passed details"},
      "cat1__ruleC1R2": {"cat": "cat1", "rule": "ruleC1R2", "status": "N/A", "details": "this is the cat1 ruleC1R2 N/A details"},
      "cat2__ruleC2R1": {"cat": "cat2", "rule": "ruleC2R1", "status": "failed", "details": "this is the cat2 ruleC2R1 failed details"},
      "cat3__ruleC3R1": {"cat": "cat3", "rule": "ruleC3R1", "status": "passed", "details": "this is the cat3 ruleC3R1 passed details"},
      "cat4__ruleC4R1": {"cat": "cat4", "rule": "ruleC4R1", "status": "N/A", "details": "this is the cat4 ruleC4R1 N/A details"},
      "cat5__ruleC5R1": {"cat": "cat5", "rule": "ruleC5R1", "status": "failed", "details": "this is the cat5 ruleC5R1 failed details"},
      "cat6__ruleC6R1": {"cat": "cat6", "rule": "ruleC6R1", "status": "passed", "details": "this is the cat6 ruleC6R1 passed details"},
      "cat7__ruleC7R1": {"cat": "cat7", "rule": "ruleC7R1", "status": "N/A", "details": "this is the cat7 ruleC7R1 N/A details"},
      "cat8__ruleC8R1": {"cat": "cat8", "rule": "ruleC8R1", "status": "failed", "details": "this is the cat8 ruleC8R1 failed details"},
      "cat9__ruleC9R1": {"cat": "cat9", "rule": "ruleC9R1", "status": "passed", "details": "this is the cat9 ruleC9R1 passed details"},
      "cat10__ruleC10R1": {"cat": "cat10", "rule": "ruleC10R1", "status": "N/A", "details": "this is the cat10 ruleC10R1 N/A details"},
      "cat11__ruleC11R1": {"cat": "cat11", "rule": "ruleC11R1", "status": "failed", "details": "this is the cat11 ruleC11R1 failed details"},
      "cat12__ruleC12R1": {"cat": "cat12", "rule": "ruleC12R1", "status": "passed", "details": "this is the cat12 ruleC12R1 passed details"},
      "cat13__ruleC13R1": {"cat": "cat13", "rule": "ruleC13R1", "status": "N/A", "details": "this is the cat13 ruleC13R1 N/A details"},
      "cat14__ruleC14R1": {"cat": "cat14", "rule": "ruleC14R1", "status": "failed", "details": "this is the cat14 ruleC14R1 failed details"},
      "cat15__ruleC15R1": {"cat": "cat15", "rule": "ruleC15R1", "status": "passed", "details": "this is the cat15 ruleC15R1 passed details"},
      "cat16__ruleC16R1": {"cat": "cat16", "rule": "ruleC16R1", "status": "N/A", "details": "this is the cat16 ruleC16R1 N/A details"},
      "cat17__ruleC17R1": {"cat": "cat17", "rule": "ruleC17R1", "status": "failed", "details": "this is the cat17 ruleC17R1 failed details"},
      "cat18__ruleC18R1": {"cat": "cat18", "rule": "ruleC18R1", "status": "passed", "details": "this is the cat18 ruleC18R1 passed details"},
      "cat19__ruleC19R1": {"cat": "cat19", "rule": "ruleC19R1", "status": "N/A", "details": "this is the cat19 ruleC19R1 N/A details"},
      "cat20__ruleC20R1": {"cat": "cat20", "rule": "ruleC20R1", "status": "failed", "details": "this is the cat20 ruleC20R1 failed details"},
      "cat21__ruleC21R1": {"cat": "cat21", "rule": "ruleC21R1", "status": "passed", "details": "this is the cat21 ruleC21R1 passed details"}
    },
    "pin_direction": "vertical",
    "pin_details": "this is the pin details of pin4"
  },
  "pin5": {
    "rules": {
      "cat1__ruleC1R1": {"cat": "cat1", "rule": "ruleC1R1", "status": "failed", "details": "this is the cat1 ruleC1R1 failed details"},
      "cat1__ruleC1R2": {"cat": "cat1", "rule": "ruleC1R2", "status": "passed", "details": "this is the cat1 ruleC1R2 passed details"},
      "cat2__ruleC2R1": {"cat": "cat2", "rule": "ruleC2R1", "status": "N/A", "details": "this is the cat2 ruleC2R1 N/A details"},
      "cat3__ruleC3R1": {"cat": "cat3", "rule": "ruleC3R1", "status": "failed", "details": "this is the cat3 ruleC3R1 failed details"},
      "cat4__ruleC4R1": {"cat": "cat4", "rule": "ruleC4R1", "status": "passed", "details": "this is the cat4 ruleC4R1 passed details"},
      "cat5__ruleC5R1": {"cat": "cat5", "rule": "ruleC5R1", "status": "N/A", "details": "this is the cat5 ruleC5R1 N/A details"},
      "cat6__ruleC6R1": {"cat": "cat6", "rule": "ruleC6R1", "status": "failed", "details": "this is the cat6 ruleC6R1 failed details"},
      "cat7__ruleC7R1": {"cat": "cat7", "rule": "ruleC7R1", "status": "passed", "details": "this is the cat7 ruleC7R1 passed details"},
      "cat8__ruleC8R1": {"cat": "cat8", "rule": "ruleC8R1", "status": "N/A", "details": "this is the cat8 ruleC8R1 N/A details"},
      "cat9__ruleC9R1": {"cat": "cat9", "rule": "ruleC9R1", "status": "failed", "details": "this is the cat9 ruleC9R1 failed details"},
      "cat10__ruleC10R1": {"cat": "cat10", "rule": "ruleC10R1", "status": "passed", "details": "this is the cat10 ruleC10R1 passed details"},
      "cat11__ruleC11R1": {"cat": "cat11", "rule": "ruleC11R1", "status": "N/A", "details": "this is the cat11 ruleC11R1 N/A details"},
      "cat12__ruleC12R1": {"cat": "cat12", "rule": "ruleC12R1", "status": "failed", "details": "this is the cat12 ruleC12R1 failed details"},
      "cat13__ruleC13R1": {"cat": "cat13", "rule": "ruleC13R1", "status": "passed", "details": "this is the cat13 ruleC13R1 passed details"},
      "cat14__ruleC14R1": {"cat": "cat14", "rule": "ruleC14R1", "status": "N/A", "details": "this is the cat14 ruleC14R1 N/A details"},
      "cat15__ruleC15R1": {"cat": "cat15", "rule": "ruleC15R1", "status": "failed", "details": "this is the cat15 ruleC15R1 failed details"},
      "cat16__ruleC16R1": {"cat": "cat16", "rule": "ruleC16R1", "status": "passed", "details": "this is the cat16 ruleC16R1 passed details"},
      "cat17__ruleC17R1": {"cat": "cat17", "rule": "ruleC17R1", "status": "N/A", "details": "this is the cat17 ruleC17R1 N/A details"},
      "cat18__ruleC18R1": {"cat": "cat18", "rule": "ruleC18R1", "status": "failed", "details": "this is the cat18 ruleC18R1 failed details"},
      "cat19__ruleC19R1": {"cat": "cat19", "rule": "ruleC19R1", "status": "passed", "details": "this is the cat19 ruleC19R1 passed details"},
      "cat20__ruleC20R1": {"cat": "cat20", "rule": "ruleC20R1", "status": "N/A", "details": "this is the cat20 ruleC20R1 N/A details"},
      "cat21__ruleC21R1": {"cat": "cat21", "rule": "ruleC21R1", "status": "failed", "details": "this is the cat21 ruleC21R1 failed details"}
    },
    "pin_direction": "horizontal",
    "pin_details": "this is the pin details of pin5"
  },
  "pin6": {
    "rules": {
      "cat1__ruleC1R1": {"cat": "cat1", "rule": "ruleC1R1", "status": "passed", "details": "this is the cat1 ruleC1R1 passed details"},
      "cat1__ruleC1R2": {"cat": "cat1", "rule": "ruleC1R2", "status": "failed", "details": "this is the cat1 ruleC1R2 failed details"},
      "cat2__ruleC2R1": {"cat": "cat2", "rule": "ruleC2R1", "status": "N/A", "details": "this is the cat2 ruleC2R1 N/A details"},
      "cat3__ruleC3R1": {"cat": "cat3", "rule": "ruleC3R1", "status": "passed", "details": "this is the cat3 ruleC3R1 passed details"},
      "cat4__ruleC4R1": {"cat": "cat4", "rule": "ruleC4R1", "status": "failed", "details": "this is the cat4 ruleC4R1 failed details"},
      "cat5__ruleC5R1": {"cat": "cat5", "rule": "ruleC5R1", "status": "N/A", "details": "this is the cat5 ruleC5R1 N/A details"},
      "cat6__ruleC6R1": {"cat": "cat6", "rule": "ruleC6R1", "status": "passed", "details": "this is the cat6 ruleC6R1 passed details"},
      "cat7__ruleC7R1": {"cat": "cat7", "rule": "ruleC7R1", "status": "failed", "details": "this is the cat7 ruleC7R1 failed details"},
      "cat8__ruleC8R1": {"cat": "cat8", "rule": "ruleC8R1", "status": "N/A", "details": "this is the cat8 ruleC8R1 N/A details"},
      "cat9__ruleC9R1": {"cat": "cat9", "rule": "ruleC9R1", "status": "passed", "details": "this is the cat9 ruleC9R1 passed details"},
      "cat10__ruleC10R1": {"cat": "cat10", "rule": "ruleC10R1", "status": "failed", "details": "this is the cat10 ruleC10R1 failed details"},
      "cat11__ruleC11R1": {"cat": "cat11", "rule": "ruleC11R1", "status": "N/A", "details": "this is the cat11 ruleC11R1 N/A details"},
      "cat12__ruleC12R1": {"cat": "cat12", "rule": "ruleC12R1", "status": "passed", "details": "this is the cat12 ruleC12R1 passed details"},
      "cat13__ruleC13R1": {"cat": "cat13", "rule": "ruleC13R1", "status": "failed", "details": "this is the cat13 ruleC13R1 failed details"},
      "cat14__ruleC14R1": {"cat": "cat14", "rule": "ruleC14R1", "status": "N/A", "details": "this is the cat14 ruleC14R1 N/A details"},
      "cat15__ruleC15R1": {"cat": "cat15", "rule": "ruleC15R1", "status": "passed", "details": "this is the cat15 ruleC15R1 passed details"},
      "cat16__ruleC16R1": {"cat": "cat16", "rule": "ruleC16R1", "status": "failed", "details": "this is the cat16 ruleC16R1 failed details"},
      "cat17__ruleC17R1": {"cat": "cat17", "rule": "ruleC17R1", "status": "N/A", "details": "this is the cat17 ruleC17R1 N/A details"},
      "cat18__ruleC18R1": {"cat": "cat18", "rule": "ruleC18R1", "status": "passed", "details": "this is the cat18 ruleC18R1 passed details"},
      "cat19__ruleC19R1": {"cat": "cat19", "rule": "ruleC19R1", "status": "failed", "details": "this is the cat19 ruleC19R1 failed details"},
      "cat20__ruleC20R1": {"cat": "cat20", "rule": "ruleC20R1", "status": "N/A", "details": "this is the cat20 ruleC20R1 N/A details"},
      "cat21__ruleC21R1": {"cat": "cat21", "rule": "ruleC21R1", "status": "passed", "details": "this is the cat21 ruleC21R1 passed details"}
    },
    "pin_direction": "horizontal",
    "pin_details": "this is the pin details of pin1"
  },
  "pin7": {
    "rules": {
      "cat1__ruleC1R1": {"cat": "cat1", "rule": "ruleC1R1", "status": "failed", "details": "this is the cat1 ruleC1R1 failed details"},
      "cat1__ruleC1R2": {"cat": "cat1", "rule": "ruleC1R2", "status": "passed", "details": "this is the cat1 ruleC1R2 passed details"},
      "cat2__ruleC2R1": {"cat": "cat2", "rule": "ruleC2R1", "status": "N/A", "details": "this is the cat2 ruleC2R1 N/A details"},
      "cat3__ruleC3R1": {"cat": "cat3", "rule": "ruleC3R1", "status": "failed", "details": "this is the cat3 ruleC3R1 failed details"},
      "cat4__ruleC4R1": {"cat": "cat4", "rule": "ruleC4R1", "status": "passed", "details": "this is the cat4 ruleC4R1 passed details"},
      "cat5__ruleC5R1": {"cat": "cat5", "rule": "ruleC5R1", "status": "N/A", "details": "this is the cat5 ruleC5R1 N/A details"},
      "cat6__ruleC6R1": {"cat": "cat6", "rule": "ruleC6R1", "status": "failed", "details": "this is the cat6 ruleC6R1 failed details"},
      "cat7__ruleC7R1": {"cat": "cat7", "rule": "ruleC7R1", "status": "passed", "details": "this is the cat7 ruleC7R1 passed details"},
      "cat8__ruleC8R1": {"cat": "cat8", "rule": "ruleC8R1", "status": "N/A", "details": "this is the cat8 ruleC8R1 N/A details"},
      "cat9__ruleC9R1": {"cat": "cat9", "rule": "ruleC9R1", "status": "failed", "details": "this is the cat9 ruleC9R1 failed details"},
      "cat10__ruleC10R1": {"cat": "cat10", "rule": "ruleC10R1", "status": "passed", "details": "this is the cat10 ruleC10R1 passed details"},
      "cat11__ruleC11R1": {"cat": "cat11", "rule": "ruleC11R1", "status": "N/A", "details": "this is the cat11 ruleC11R1 N/A details"},
      "cat12__ruleC12R1": {"cat": "cat12", "rule": "ruleC12R1", "status": "failed", "details": "this is the cat12 ruleC12R1 failed details"},
      "cat13__ruleC13R1": {"cat": "cat13", "rule": "ruleC13R1", "status": "passed", "details": "this is the cat13 ruleC13R1 passed details"},
      "cat14__ruleC14R1": {"cat": "cat14", "rule": "ruleC14R1", "status": "N/A", "details": "this is the cat14 ruleC14R1 N/A details"},
      "cat15__ruleC15R1": {"cat": "cat15", "rule": "ruleC15R1", "status": "failed", "details": "this is the cat15 ruleC15R1 failed details"},
      "cat16__ruleC16R1": {"cat": "cat16", "rule": "ruleC16R1", "status": "passed", "details": "this is the cat16 ruleC16R1 passed details"},
      "cat17__ruleC17R1": {"cat": "cat17", "rule": "ruleC17R1", "status": "N/A", "details": "this is the cat17 ruleC17R1 N/A details"},
      "cat18__ruleC18R1": {"cat": "cat18", "rule": "ruleC18R1", "status": "failed", "details": "this is the cat18 ruleC18R1 failed details"},
      "cat19__ruleC19R1": {"cat": "cat19", "rule": "ruleC19R1", "status": "passed", "details": "this is the cat19 ruleC19R1 passed details"},
      "cat20__ruleC20R1": {"cat": "cat20", "rule": "ruleC20R1", "status": "N/A", "details": "this is the cat20 ruleC20R1 N/A details"},
      "cat21__ruleC21R1": {"cat": "cat21", "rule": "ruleC21R1", "status": "failed", "details": "this is the cat21 ruleC21R1 failed details"}
    },
    "pin_direction": "vertical",
    "pin_details": "this is the pin details of pin2"
  },
  "pin8": {
    "rules": {
      "cat1__ruleC1R1": {"cat": "cat1", "rule": "ruleC1R1", "status": "N/A", "details": "this is the cat1 ruleC1R1 N/A details"},
      "cat1__ruleC1R2": {"cat": "cat1", "rule": "ruleC1R2", "status": "failed", "details": "this is the cat1 ruleC1R2 failed details"},
      "cat2__ruleC2R1": {"cat": "cat2", "rule": "ruleC2R1", "status": "passed", "details": "this is the cat2 ruleC2R1 passed details"},
      "cat3__ruleC3R1": {"cat": "cat3", "rule": "ruleC3R1", "status": "N/A", "details": "this is the cat3 ruleC3R1 N/A details"},
      "cat4__ruleC4R1": {"cat": "cat4", "rule": "ruleC4R1", "status": "failed", "details": "this is the cat4 ruleC4R1 failed details"},
      "cat5__ruleC5R1": {"cat": "cat5", "rule": "ruleC5R1", "status": "passed", "details": "this is the cat5 ruleC5R1 passed details"},
      "cat6__ruleC6R1": {"cat": "cat6", "rule": "ruleC6R1", "status": "N/A", "details": "this is the cat6 ruleC6R1 N/A details"},
      "cat7__ruleC7R1": {"cat": "cat7", "rule": "ruleC7R1", "status": "failed", "details": "this is the cat7 ruleC7R1 failed details"},
      "cat8__ruleC8R1": {"cat": "cat8", "rule": "ruleC8R1", "status": "passed", "details": "this is the cat8 ruleC8R1 passed details"},
      "cat9__ruleC9R1": {"cat": "cat9", "rule": "ruleC9R1", "status": "N/A", "details": "this is the cat9 ruleC9R1 N/A details"},
      "cat10__ruleC10R1": {"cat": "cat10", "rule": "ruleC10R1", "status": "failed", "details": "this is the cat10 ruleC10R1 failed details"},
      "cat11__ruleC11R1": {"cat": "cat11", "rule": "ruleC11R1", "status": "passed", "details": "this is the cat11 ruleC11R1 passed details"},
      "cat12__ruleC12R1": {"cat": "cat12", "rule": "ruleC12R1", "status": "N/A", "details": "this is the cat12 ruleC12R1 N/A details"},
      "cat13__ruleC13R1": {"cat": "cat13", "rule": "ruleC13R1", "status": "failed", "details": "this is the cat13 ruleC13R1 failed details"},
      "cat14__ruleC14R1": {"cat": "cat14", "rule": "ruleC14R1", "status": "passed", "details": "this is the cat14 ruleC14R1 passed details"},
      "cat15__ruleC15R1": {"cat": "cat15", "rule": "ruleC15R1", "status": "N/A", "details": "this is the cat15 ruleC15R1 N/A details"},
      "cat16__ruleC16R1": {"cat": "cat16", "rule": "ruleC16R1", "status": "failed", "details": "this is the cat16 ruleC16R1 failed details"},
      "cat17__ruleC17R1": {"cat": "cat17", "rule": "ruleC17R1", "status": "passed", "details": "this is the cat17 ruleC17R1 passed details"},
      "cat18__ruleC18R1": {"cat": "cat18", "rule": "ruleC18R1", "status": "N/A", "details": "this is the cat18 ruleC18R1 N/A details"},
      "cat19__ruleC19R1": {"cat": "cat19", "rule": "ruleC19R1", "status": "failed", "details": "this is the cat19 ruleC19R1 failed details"},
      "cat20__ruleC20R1": {"cat": "cat20", "rule": "ruleC20R1", "status": "passed", "details": "this is the cat20 ruleC20R1 passed details"},
      "cat21__ruleC21R1": {"cat": "cat21", "rule": "ruleC21R1", "status": "N/A", "details": "this is the cat21 ruleC21R1 N/A details"}
    },
    "pin_direction": "horizontal",
    "pin_details": "this is the pin details of pin3"
  },
  "pin9": {
    "rules": {
      "cat1__ruleC1R1": {"cat": "cat1", "rule": "ruleC1R1", "status": "passed", "details": "this is the cat1 ruleC1R1 passed details"},
      "cat1__ruleC1R2": {"cat": "cat1", "rule": "ruleC1R2", "status": "N/A", "details": "this is the cat1 ruleC1R2 N/A details"},
      "cat2__ruleC2R1": {"cat": "cat2", "rule": "ruleC2R1", "status": "failed", "details": "this is the cat2 ruleC2R1 failed details"},
      "cat3__ruleC3R1": {"cat": "cat3", "rule": "ruleC3R1", "status": "passed", "details": "this is the cat3 ruleC3R1 passed details"},
      "cat4__ruleC4R1": {"cat": "cat4", "rule": "ruleC4R1", "status": "N/A", "details": "this is the cat4 ruleC4R1 N/A details"},
      "cat5__ruleC5R1": {"cat": "cat5", "rule": "ruleC5R1", "status": "failed", "details": "this is the cat5 ruleC5R1 failed details"},
      "cat6__ruleC6R1": {"cat": "cat6", "rule": "ruleC6R1", "status": "passed", "details": "this is the cat6 ruleC6R1 passed details"},
      "cat7__ruleC7R1": {"cat": "cat7", "rule": "ruleC7R1", "status": "N/A", "details": "this is the cat7 ruleC7R1 N/A details"},
      "cat8__ruleC8R1": {"cat": "cat8", "rule": "ruleC8R1", "status": "failed", "details": "this is the cat8 ruleC8R1 failed details"},
      "cat9__ruleC9R1": {"cat": "cat9", "rule": "ruleC9R1", "status": "passed", "details": "this is the cat9 ruleC9R1 passed details"},
      "cat10__ruleC10R1": {"cat": "cat10", "rule": "ruleC10R1", "status": "N/A", "details": "this is the cat10 ruleC10R1 N/A details"},
      "cat11__ruleC11R1": {"cat": "cat11", "rule": "ruleC11R1", "status": "failed", "details": "this is the cat11 ruleC11R1 failed details"},
      "cat12__ruleC12R1": {"cat": "cat12", "rule": "ruleC12R1", "status": "passed", "details": "this is the cat12 ruleC12R1 passed details"},
      "cat13__ruleC13R1": {"cat": "cat13", "rule": "ruleC13R1", "status": "N/A", "details": "this is the cat13 ruleC13R1 N/A details"},
      "cat14__ruleC14R1": {"cat": "cat14", "rule": "ruleC14R1", "status": "failed", "details": "this is the cat14 ruleC14R1 failed details"},
      "cat15__ruleC15R1": {"cat": "cat15", "rule": "ruleC15R1", "status": "passed", "details": "this is the cat15 ruleC15R1 passed details"},
      "cat16__ruleC16R1": {"cat": "cat16", "rule": "ruleC16R1", "status": "N/A", "details": "this is the cat16 ruleC16R1 N/A details"},
      "cat17__ruleC17R1": {"cat": "cat17", "rule": "ruleC17R1", "status": "failed", "details": "this is the cat17 ruleC17R1 failed details"},
      "cat18__ruleC18R1": {"cat": "cat18", "rule": "ruleC18R1", "status": "passed", "details": "this is the cat18 ruleC18R1 passed details"},
      "cat19__ruleC19R1": {"cat": "cat19", "rule": "ruleC19R1", "status": "N/A", "details": "this is the cat19 ruleC19R1 N/A details"},
      "cat20__ruleC20R1": {"cat": "cat20", "rule": "ruleC20R1", "status": "failed", "details": "this is the cat20 ruleC20R1 failed details"},
      "cat21__ruleC21R1": {"cat": "cat21", "rule": "ruleC21R1", "status": "passed", "details": "this is the cat21 ruleC21R1 passed details"}
    },
    "pin_direction": "vertical",
    "pin_details": "this is the pin details of pin4"
  },
  "pin10": {
    "rules": {
      "cat1__ruleC1R1": {"cat": "cat1", "rule": "ruleC1R1", "status": "failed", "details": "this is the cat1 ruleC1R1 failed details"},
      "cat1__ruleC1R2": {"cat": "cat1", "rule": "ruleC1R2", "status": "passed", "details": "this is the cat1 ruleC1R2 passed details"},
      "cat2__ruleC2R1": {"cat": "cat2", "rule": "ruleC2R1", "status": "N/A", "details": "this is the cat2 ruleC2R1 N/A details"},
      "cat3__ruleC3R1": {"cat": "cat3", "rule": "ruleC3R1", "status": "failed", "details": "this is the cat3 ruleC3R1 failed details"},
      "cat4__ruleC4R1": {"cat": "cat4", "rule": "ruleC4R1", "status": "passed", "details": "this is the cat4 ruleC4R1 passed details"},
      "cat5__ruleC5R1": {"cat": "cat5", "rule": "ruleC5R1", "status": "N/A", "details": "this is the cat5 ruleC5R1 N/A details"},
      "cat6__ruleC6R1": {"cat": "cat6", "rule": "ruleC6R1", "status": "failed", "details": "this is the cat6 ruleC6R1 failed details"},
      "cat7__ruleC7R1": {"cat": "cat7", "rule": "ruleC7R1", "status": "passed", "details": "this is the cat7 ruleC7R1 passed details"},
      "cat8__ruleC8R1": {"cat": "cat8", "rule": "ruleC8R1", "status": "N/A", "details": "this is the cat8 ruleC8R1 N/A details"},
      "cat9__ruleC9R1": {"cat": "cat9", "rule": "ruleC9R1", "status": "failed", "details": "this is the cat9 ruleC9R1 failed details"},
      "cat10__ruleC10R1": {"cat": "cat10", "rule": "ruleC10R1", "status": "passed", "details": "this is the cat10 ruleC10R1 passed details"},
      "cat11__ruleC11R1": {"cat": "cat11", "rule": "ruleC11R1", "status": "N/A", "details": "this is the cat11 ruleC11R1 N/A details"},
      "cat12__ruleC12R1": {"cat": "cat12", "rule": "ruleC12R1", "status": "failed", "details": "this is the cat12 ruleC12R1 failed details"},
      "cat13__ruleC13R1": {"cat": "cat13", "rule": "ruleC13R1", "status": "passed", "details": "this is the cat13 ruleC13R1 passed details"},
      "cat14__ruleC14R1": {"cat": "cat14", "rule": "ruleC14R1", "status": "N/A", "details": "this is the cat14 ruleC14R1 N/A details"},
      "cat15__ruleC15R1": {"cat": "cat15", "rule": "ruleC15R1", "status": "failed", "details": "this is the cat15 ruleC15R1 failed details"},
      "cat16__ruleC16R1": {"cat": "cat16", "rule": "ruleC16R1", "status": "passed", "details": "this is the cat16 ruleC16R1 passed details"},
      "cat17__ruleC17R1": {"cat": "cat17", "rule": "ruleC17R1", "status": "N/A", "details": "this is the cat17 ruleC17R1 N/A details"},
      "cat18__ruleC18R1": {"cat": "cat18", "rule": "ruleC18R1", "status": "failed", "details": "this is the cat18 ruleC18R1 failed details"},
      "cat19__ruleC19R1": {"cat": "cat19", "rule": "ruleC19R1", "status": "passed", "details": "this is the cat19 ruleC19R1 passed details"},
      "cat20__ruleC20R1": {"cat": "cat20", "rule": "ruleC20R1", "status": "N/A", "details": "this is the cat20 ruleC20R1 N/A details"},
      "cat21__ruleC21R1": {"cat": "cat21", "rule": "ruleC21R1", "status": "failed", "details": "this is the cat21 ruleC21R1 failed details"}
    },
    "pin_direction": "horizontal",
    "pin_details": "this is the pin details of pin5"
  },
  "pin11": {
    "rules": {
      "cat1__ruleC1R1": {"cat": "cat1", "rule": "ruleC1R1", "status": "passed", "details": "this is the cat1 ruleC1R1 passed details"},
      "cat1__ruleC1R2": {"cat": "cat1", "rule": "ruleC1R2", "status": "failed", "details": "this is the cat1 ruleC1R2 failed details"},
      "cat2__ruleC2R1": {"cat": "cat2", "rule": "ruleC2R1", "status": "N/A", "details": "this is the cat2 ruleC2R1 N/A details"},
      "cat3__ruleC3R1": {"cat": "cat3", "rule": "ruleC3R1", "status": "passed", "details": "this is the cat3 ruleC3R1 passed details"},
      "cat4__ruleC4R1": {"cat": "cat4", "rule": "ruleC4R1", "status": "failed", "details": "this is the cat4 ruleC4R1 failed details"},
      "cat5__ruleC5R1": {"cat": "cat5", "rule": "ruleC5R1", "status": "N/A", "details": "this is the cat5 ruleC5R1 N/A details"},
      "cat6__ruleC6R1": {"cat": "cat6", "rule": "ruleC6R1", "status": "passed", "details": "this is the cat6 ruleC6R1 passed details"},
      "cat7__ruleC7R1": {"cat": "cat7", "rule": "ruleC7R1", "status": "failed", "details": "this is the cat7 ruleC7R1 failed details"},
      "cat8__ruleC8R1": {"cat": "cat8", "rule": "ruleC8R1", "status": "N/A", "details": "this is the cat8 ruleC8R1 N/A details"},
      "cat9__ruleC9R1": {"cat": "cat9", "rule": "ruleC9R1", "status": "passed", "details": "this is the cat9 ruleC9R1 passed details"},
      "cat10__ruleC10R1": {"cat": "cat10", "rule": "ruleC10R1", "status": "failed", "details": "this is the cat10 ruleC10R1 failed details"},
      "cat11__ruleC11R1": {"cat": "cat11", "rule": "ruleC11R1", "status": "N/A", "details": "this is the cat11 ruleC11R1 N/A details"},
      "cat12__ruleC12R1": {"cat": "cat12", "rule": "ruleC12R1", "status": "passed", "details": "this is the cat12 ruleC12R1 passed details"},
      "cat13__ruleC13R1": {"cat": "cat13", "rule": "ruleC13R1", "status": "failed", "details": "this is the cat13 ruleC13R1 failed details"},
      "cat14__ruleC14R1": {"cat": "cat14", "rule": "ruleC14R1", "status": "N/A", "details": "this is the cat14 ruleC14R1 N/A details"},
      "cat15__ruleC15R1": {"cat": "cat15", "rule": "ruleC15R1", "status": "passed", "details": "this is the cat15 ruleC15R1 passed details"},
      "cat16__ruleC16R1": {"cat": "cat16", "rule": "ruleC16R1", "status": "failed", "details": "this is the cat16 ruleC16R1 failed details"},
      "cat17__ruleC17R1": {"cat": "cat17", "rule": "ruleC17R1", "status": "N/A", "details": "this is the cat17 ruleC17R1 N/A details"},
      "cat18__ruleC18R1": {"cat": "cat18", "rule": "ruleC18R1", "status": "passed", "details": "this is the cat18 ruleC18R1 passed details"},
      "cat19__ruleC19R1": {"cat": "cat19", "rule": "ruleC19R1", "status": "failed", "details": "this is the cat19 ruleC19R1 failed details"},
      "cat20__ruleC20R1": {"cat": "cat20", "rule": "ruleC20R1", "status": "N/A", "details": "this is the cat20 ruleC20R1 N/A details"},
      "cat21__ruleC21R1": {"cat": "cat21", "rule": "ruleC21R1", "status": "passed", "details": "this is the cat21 ruleC21R1 passed details"}
    },
    "pin_direction": "horizontal",
    "pin_details": "this is the pin details of pin1"
  },
  "pin12": {
    "rules": {
      "cat1__ruleC1R1": {"cat": "cat1", "rule": "ruleC1R1", "status": "failed", "details": "this is the cat1 ruleC1R1 failed details"},
      "cat1__ruleC1R2": {"cat": "cat1", "rule": "ruleC1R2", "status": "passed", "details": "this is the cat1 ruleC1R2 passed details"},
      "cat2__ruleC2R1": {"cat": "cat2", "rule": "ruleC2R1", "status": "N/A", "details": "this is the cat2 ruleC2R1 N/A details"},
      "cat3__ruleC3R1": {"cat": "cat3", "rule": "ruleC3R1", "status": "failed", "details": "this is the cat3 ruleC3R1 failed details"},
      "cat4__ruleC4R1": {"cat": "cat4", "rule": "ruleC4R1", "status": "passed", "details": "this is the cat4 ruleC4R1 passed details"},
      "cat5__ruleC5R1": {"cat": "cat5", "rule": "ruleC5R1", "status": "N/A", "details": "this is the cat5 ruleC5R1 N/A details"},
      "cat6__ruleC6R1": {"cat": "cat6", "rule": "ruleC6R1", "status": "failed", "details": "this is the cat6 ruleC6R1 failed details"},
      "cat7__ruleC7R1": {"cat": "cat7", "rule": "ruleC7R1", "status": "passed", "details": "this is the cat7 ruleC7R1 passed details"},
      "cat8__ruleC8R1": {"cat": "cat8", "rule": "ruleC8R1", "status": "N/A", "details": "this is the cat8 ruleC8R1 N/A details"},
      "cat9__ruleC9R1": {"cat": "cat9", "rule": "ruleC9R1", "status": "failed", "details": "this is the cat9 ruleC9R1 failed details"},
      "cat10__ruleC10R1": {"cat": "cat10", "rule": "ruleC10R1", "status": "passed", "details": "this is the cat10 ruleC10R1 passed details"},
      "cat11__ruleC11R1": {"cat": "cat11", "rule": "ruleC11R1", "status": "N/A", "details": "this is the cat11 ruleC11R1 N/A details"},
      "cat12__ruleC12R1": {"cat": "cat12", "rule": "ruleC12R1", "status": "failed", "details": "this is the cat12 ruleC12R1 failed details"},
      "cat13__ruleC13R1": {"cat": "cat13", "rule": "ruleC13R1", "status": "passed", "details": "this is the cat13 ruleC13R1 passed details"},
      "cat14__ruleC14R1": {"cat": "cat14", "rule": "ruleC14R1", "status": "N/A", "details": "this is the cat14 ruleC14R1 N/A details"},
      "cat15__ruleC15R1": {"cat": "cat15", "rule": "ruleC15R1", "status": "failed", "details": "this is the cat15 ruleC15R1 failed details"},
      "cat16__ruleC16R1": {"cat": "cat16", "rule": "ruleC16R1", "status": "passed", "details": "this is the cat16 ruleC16R1 passed details"},
      "cat17__ruleC17R1": {"cat": "cat17", "rule": "ruleC17R1", "status": "N/A", "details": "this is the cat17 ruleC17R1 N/A details"},
      "cat18__ruleC18R1": {"cat": "cat18", "rule": "ruleC18R1", "status": "failed", "details": "this is the cat18 ruleC18R1 failed details"},
      "cat19__ruleC19R1": {"cat": "cat19", "rule": "ruleC19R1", "status": "passed", "details": "this is the cat19 ruleC19R1 passed details"},
      "cat20__ruleC20R1": {"cat": "cat20", "rule": "ruleC20R1", "status": "N/A", "details": "this is the cat20 ruleC20R1 N/A details"},
      "cat21__ruleC21R1": {"cat": "cat21", "rule": "ruleC21R1", "status": "failed", "details": "this is the cat21 ruleC21R1 failed details"}
    },
    "pin_direction": "vertical",
    "pin_details": "this is the pin details of pin2"
  },
  "pin13": {
    "rules": {
      "cat1__ruleC1R1": {"cat": "cat1", "rule": "ruleC1R1", "status": "N/A", "details": "this is the cat1 ruleC1R1 N/A details"},
      "cat1__ruleC1R2": {"cat": "cat1", "rule": "ruleC1R2", "status": "failed", "details": "this is the cat1 ruleC1R2 failed details"},
      "cat2__ruleC2R1": {"cat": "cat2", "rule": "ruleC2R1", "status": "passed", "details": "this is the cat2 ruleC2R1 passed details"},
      "cat3__ruleC3R1": {"cat": "cat3", "rule": "ruleC3R1", "status": "N/A", "details": "this is the cat3 ruleC3R1 N/A details"},
      "cat4__ruleC4R1": {"cat": "cat4", "rule": "ruleC4R1", "status": "failed", "details": "this is the cat4 ruleC4R1 failed details"},
      "cat5__ruleC5R1": {"cat": "cat5", "rule": "ruleC5R1", "status": "passed", "details": "this is the cat5 ruleC5R1 passed details"},
      "cat6__ruleC6R1": {"cat": "cat6", "rule": "ruleC6R1", "status": "N/A", "details": "this is the cat6 ruleC6R1 N/A details"},
      "cat7__ruleC7R1": {"cat": "cat7", "rule": "ruleC7R1", "status": "failed", "details": "this is the cat7 ruleC7R1 failed details"},
      "cat8__ruleC8R1": {"cat": "cat8", "rule": "ruleC8R1", "status": "passed", "details": "this is the cat8 ruleC8R1 passed details"},
      "cat9__ruleC9R1": {"cat": "cat9", "rule": "ruleC9R1", "status": "N/A", "details": "this is the cat9 ruleC9R1 N/A details"},
      "cat10__ruleC10R1": {"cat": "cat10", "rule": "ruleC10R1", "status": "failed", "details": "this is the cat10 ruleC10R1 failed details"},
      "cat11__ruleC11R1": {"cat": "cat11", "rule": "ruleC11R1", "status": "passed", "details": "this is the cat11 ruleC11R1 passed details"},
      "cat12__ruleC12R1": {"cat": "cat12", "rule": "ruleC12R1", "status": "N/A", "details": "this is the cat12 ruleC12R1 N/A details"},
      "cat13__ruleC13R1": {"cat": "cat13", "rule": "ruleC13R1", "status": "failed", "details": "this is the cat13 ruleC13R1 failed details"},
      "cat14__ruleC14R1": {"cat": "cat14", "rule": "ruleC14R1", "status": "passed", "details": "this is the cat14 ruleC14R1 passed details"},
      "cat15__ruleC15R1": {"cat": "cat15", "rule": "ruleC15R1", "status": "N/A", "details": "this is the cat15 ruleC15R1 N/A details"},
      "cat16__ruleC16R1": {"cat": "cat16", "rule": "ruleC16R1", "status": "failed", "details": "this is the cat16 ruleC16R1 failed details"},
      "cat17__ruleC17R1": {"cat": "cat17", "rule": "ruleC17R1", "status": "passed", "details": "this is the cat17 ruleC17R1 passed details"},
      "cat18__ruleC18R1": {"cat": "cat18", "rule": "ruleC18R1", "status": "N/A", "details": "this is the cat18 ruleC18R1 N/A details"},
      "cat19__ruleC19R1": {"cat": "cat19", "rule": "ruleC19R1", "status": "failed", "details": "this is the cat19 ruleC19R1 failed details"},
      "cat20__ruleC20R1": {"cat": "cat20", "rule": "ruleC20R1", "status": "passed", "details": "this is the cat20 ruleC20R1 passed details"},
      "cat21__ruleC21R1": {"cat": "cat21", "rule": "ruleC21R1", "status": "N/A", "details": "this is the cat21 ruleC21R1 N/A details"}
    },
    "pin_direction": "horizontal",
    "pin_details": "this is the pin details of pin3"
  },
  "pin14": {
    "rules": {
      "cat1__ruleC1R1": {"cat": "cat1", "rule": "ruleC1R1", "status": "passed", "details": "this is the cat1 ruleC1R1 passed details"},
      "cat1__ruleC1R2": {"cat": "cat1", "rule": "ruleC1R2", "status": "N/A", "details": "this is the cat1 ruleC1R2 N/A details"},
      "cat2__ruleC2R1": {"cat": "cat2", "rule": "ruleC2R1", "status": "failed", "details": "this is the cat2 ruleC2R1 failed details"},
      "cat3__ruleC3R1": {"cat": "cat3", "rule": "ruleC3R1", "status": "passed", "details": "this is the cat3 ruleC3R1 passed details"},
      "cat4__ruleC4R1": {"cat": "cat4", "rule": "ruleC4R1", "status": "N/A", "details": "this is the cat4 ruleC4R1 N/A details"},
      "cat5__ruleC5R1": {"cat": "cat5", "rule": "ruleC5R1", "status": "failed", "details": "this is the cat5 ruleC5R1 failed details"},
      "cat6__ruleC6R1": {"cat": "cat6", "rule": "ruleC6R1", "status": "passed", "details": "this is the cat6 ruleC6R1 passed details"},
      "cat7__ruleC7R1": {"cat": "cat7", "rule": "ruleC7R1", "status": "N/A", "details": "this is the cat7 ruleC7R1 N/A details"},
      "cat8__ruleC8R1": {"cat": "cat8", "rule": "ruleC8R1", "status": "failed", "details": "this is the cat8 ruleC8R1 failed details"},
      "cat9__ruleC9R1": {"cat": "cat9", "rule": "ruleC9R1", "status": "passed", "details": "this is the cat9 ruleC9R1 passed details"},
      "cat10__ruleC10R1": {"cat": "cat10", "rule": "ruleC10R1", "status": "N/A", "details": "this is the cat10 ruleC10R1 N/A details"},
      "cat11__ruleC11R1": {"cat": "cat11", "rule": "ruleC11R1", "status": "failed", "details": "this is the cat11 ruleC11R1 failed details"},
      "cat12__ruleC12R1": {"cat": "cat12", "rule": "ruleC12R1", "status": "passed", "details": "this is the cat12 ruleC12R1 passed details"},
      "cat13__ruleC13R1": {"cat": "cat13", "rule": "ruleC13R1", "status": "N/A", "details": "this is the cat13 ruleC13R1 N/A details"},
      "cat14__ruleC14R1": {"cat": "cat14", "rule": "ruleC14R1", "status": "failed", "details": "this is the cat14 ruleC14R1 failed details"},
      "cat15__ruleC15R1": {"cat": "cat15", "rule": "ruleC15R1", "status": "passed", "details": "this is the cat15 ruleC15R1 passed details"},
      "cat16__ruleC16R1": {"cat": "cat16", "rule": "ruleC16R1", "status": "N/A", "details": "this is the cat16 ruleC16R1 N/A details"},
      "cat17__ruleC17R1": {"cat": "cat17", "rule": "ruleC17R1", "status": "failed", "details": "this is the cat17 ruleC17R1 failed details"},
      "cat18__ruleC18R1": {"cat": "cat18", "rule": "ruleC18R1", "status": "passed", "details": "this is the cat18 ruleC18R1 passed details"},
      "cat19__ruleC19R1": {"cat": "cat19", "rule": "ruleC19R1", "status": "N/A", "details": "this is the cat19 ruleC19R1 N/A details"},
      "cat20__ruleC20R1": {"cat": "cat20", "rule": "ruleC20R1", "status": "failed", "details": "this is the cat20 ruleC20R1 failed details"},
      "cat21__ruleC21R1": {"cat": "cat21", "rule": "ruleC21R1", "status": "passed", "details": "this is the cat21 ruleC21R1 passed details"}
    },
    "pin_direction": "vertical",
    "pin_details": "this is the pin details of pin4"
  },
  "pin15": {
    "rules": {
      "cat1__ruleC1R1": {"cat": "cat1", "rule": "ruleC1R1", "status": "failed", "details": "this is the cat1 ruleC1R1 failed details"},
      "cat1__ruleC1R2": {"cat": "cat1", "rule": "ruleC1R2", "status": "passed", "details": "this is the cat1 ruleC1R2 passed details"},
      "cat2__ruleC2R1": {"cat": "cat2", "rule": "ruleC2R1", "status": "N/A", "details": "this is the cat2 ruleC2R1 N/A details"},
      "cat3__ruleC3R1": {"cat": "cat3", "rule": "ruleC3R1", "status": "failed", "details": "this is the cat3 ruleC3R1 failed details"},
      "cat4__ruleC4R1": {"cat": "cat4", "rule": "ruleC4R1", "status": "passed", "details": "this is the cat4 ruleC4R1 passed details"},
      "cat5__ruleC5R1": {"cat": "cat5", "rule": "ruleC5R1", "status": "N/A", "details": "this is the cat5 ruleC5R1 N/A details"},
      "cat6__ruleC6R1": {"cat": "cat6", "rule": "ruleC6R1", "status": "failed", "details": "this is the cat6 ruleC6R1 failed details"},
      "cat7__ruleC7R1": {"cat": "cat7", "rule": "ruleC7R1", "status": "passed", "details": "this is the cat7 ruleC7R1 passed details"},
      "cat8__ruleC8R1": {"cat": "cat8", "rule": "ruleC8R1", "status": "N/A", "details": "this is the cat8 ruleC8R1 N/A details"},
      "cat9__ruleC9R1": {"cat": "cat9", "rule": "ruleC9R1", "status": "failed", "details": "this is the cat9 ruleC9R1 failed details"},
      "cat10__ruleC10R1": {"cat": "cat10", "rule": "ruleC10R1", "status": "passed", "details": "this is the cat10 ruleC10R1 passed details"},
      "cat11__ruleC11R1": {"cat": "cat11", "rule": "ruleC11R1", "status": "N/A", "details": "this is the cat11 ruleC11R1 N/A details"},
      "cat12__ruleC12R1": {"cat": "cat12", "rule": "ruleC12R1", "status": "failed", "details": "this is the cat12 ruleC12R1 failed details"},
      "cat13__ruleC13R1": {"cat": "cat13", "rule": "ruleC13R1", "status": "passed", "details": "this is the cat13 ruleC13R1 passed details"},
      "cat14__ruleC14R1": {"cat": "cat14", "rule": "ruleC14R1", "status": "N/A", "details": "this is the cat14 ruleC14R1 N/A details"},
      "cat15__ruleC15R1": {"cat": "cat15", "rule": "ruleC15R1", "status": "failed", "details": "this is the cat15 ruleC15R1 failed details"},
      "cat16__ruleC16R1": {"cat": "cat16", "rule": "ruleC16R1", "status": "passed", "details": "this is the cat16 ruleC16R1 passed details"},
      "cat17__ruleC17R1": {"cat": "cat17", "rule": "ruleC17R1", "status": "N/A", "details": "this is the cat17 ruleC17R1 N/A details"},
      "cat18__ruleC18R1": {"cat": "cat18", "rule": "ruleC18R1", "status": "failed", "details": "this is the cat18 ruleC18R1 failed details"},
      "cat19__ruleC19R1": {"cat": "cat19", "rule": "ruleC19R1", "status": "passed", "details": "this is the cat19 ruleC19R1 passed details"},
      "cat20__ruleC20R1": {"cat": "cat20", "rule": "ruleC20R1", "status": "N/A", "details": "this is the cat20 ruleC20R1 N/A details"},
      "cat21__ruleC21R1": {"cat": "cat21", "rule": "ruleC21R1", "status": "failed", "details": "this is the cat21 ruleC21R1 failed details"}
    },
    "pin_direction": "horizontal",
    "pin_details": "this is the pin details of pin5"
  }
}